baseURL = "http://underfjellet.no/"
languageCode = "no"
title = "Dyrlegen Under Fjellet"
theme = "hugo-serif-theme"

[params.logo]
mobile = "images/du_logo.png"
mobile_height = "36px"
desktop = "images/du_logo.png"
desktop_height = "100px"
alt = "Dyrlegen Underfjellet"

[params.homepage]
show_contact_box = true # show / hide the contaxt box on the homepage
show_services_button = true  # show / hide the "view all services" button

[menu]
  # Main Menu
  # [[menu.main]]
  #     name = "Tjenester"
  #     url = "/tjenester/"
  #     weight = 4

  [[menu.main]]
      name = "Hjem"
      url = "/"
      weight = 4

  [[menu.main]]
      name = "Om oss"
      url = "/omoss/"
      weight = 8

  [[menu.main]]
      name = "Priser"
      url = "/priser/"
      weight = 8

[params.footer]
copyright_text = '&#169; 2021-2026 Dyrlegen Under Fjellet'

[params.fonts]
# sets the google font link in layouts/partials/google-fonts.html
google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
heading = "Playfair Display"
base = "Source Sans Pro"

[params.colors]
primary = "#67a2d5"
black = "#2f2f41"
white = "#ffffff"
white_offset = "#f6f7ff"
grey = "#5C5A5A"